// SmartRide System Constants & Configurations

export const VEHICLE_TYPES = {
  BIKE: {
    id: 'bike',
    name: 'Bike',
    type: 'bike',
    capacity: 1,
    baseFare: 25,
    perKm: 9,
    perMin: 1.5,
    icon: 'Bike',
    estimatedSpeedKmh: 35,
    description: 'Quickest for single riders & tight traffic',
    allowSharing: false,
    tagline: 'Fastest in traffic',
  },
  AUTO_PRIVATE: {
    id: 'auto_private',
    name: 'Private Auto',
    type: 'auto',
    capacity: 3,
    baseFare: 40,
    perKm: 14,
    perMin: 2.0,
    icon: 'Car',
    estimatedSpeedKmh: 30,
    description: 'Doorstep pick-up for up to 3 people',
    allowSharing: false,
    tagline: 'Economical private ride',
  },
  AUTO_SHARE: {
    id: 'auto_share',
    name: 'Share Auto',
    type: 'auto',
    capacity: 3,
    baseFare: 25,
    perKm: 8.5,
    perMin: 1.2,
    icon: 'Users',
    estimatedSpeedKmh: 28,
    description: 'Share auto with commuters along your route',
    allowSharing: true,
    sharingDiscountPercent: 35,
    tagline: 'Save up to 35%',
  },
  CAB_PRIVATE: {
    id: 'cab_private',
    name: 'Private Cab',
    type: 'cab',
    capacity: 4,
    baseFare: 80,
    perKm: 18,
    perMin: 2.5,
    icon: 'CarFront',
    estimatedSpeedKmh: 40,
    description: 'Comfortable AC sedan/hatchback just for you',
    allowSharing: false,
    tagline: 'Comfort & privacy',
  },
  CAB_SHARE: {
    id: 'cab_share',
    name: 'Share Cab',
    type: 'cab',
    capacity: 4,
    baseFare: 50,
    perKm: 11,
    perMin: 1.8,
    icon: 'Share2',
    estimatedSpeedKmh: 38,
    description: 'Share cab with 1-3 passengers with aligned route',
    allowSharing: true,
    sharingDiscountPercent: 45,
    tagline: 'Save up to 45%',
  },
};

export const MATCHING_THRESHOLDS = {
  MAX_PICKUP_DETOUR_KM: 2.5,      // Max extra km to pick up extra passenger
  MAX_DESTINATION_DETOUR_KM: 2.0, // Max extra km for drop-off point
  MAX_DETOUR_TIME_MINS: 6,       // Maximum extra delay added to original passenger
  MIN_ROUTE_OVERLAP_PERCENT: 65,  // Minimum overlapping route alignment percentage
  MAX_VEHICLE_CAPACITY: 4,
};

export const PLATFORM_CONFIG = {
  PLATFORM_COMMISSION_PERCENT: 15,
  DRIVER_SHARE_BONUS_PERCENT: 20, // Extra earning incentive for taking shared rides
  DEFAULT_SURGE_MULTIPLIER: 1.0,
  TAX_PERCENT: 5,
};

// Popular mock spots for interactive demo matching (Bangalore Tech Corridor context)
export const MOCK_LOCATIONS = [
  {
    id: 'loc_1',
    name: 'Indiranagar Metro Station',
    address: '100 Feet Rd, Stage 2, Indiranagar, Bengaluru',
    lat: 12.9784,
    lng: 77.6408,
    category: 'metro',
  },
  {
    id: 'loc_2',
    name: 'Koramangala Sony World Signal',
    address: '80 Feet Rd, 4th Block, Koramangala, Bengaluru',
    lat: 12.9352,
    lng: 77.6245,
    category: 'popular',
  },
  {
    id: 'loc_3',
    name: 'Embassy TechVillage (ORR)',
    address: 'Outer Ring Rd, Devarabesanahalli, Bellandur, Bengaluru',
    lat: 12.9260,
    lng: 77.6934,
    category: 'work',
  },
  {
    id: 'loc_4',
    name: 'MG Road Metro Station',
    address: 'Mahatma Gandhi Rd, Bengaluru',
    lat: 12.9756,
    lng: 77.6066,
    category: 'metro',
  },
  {
    id: 'loc_5',
    name: 'HSR Layout BDA Complex',
    address: '27th Main Rd, Sector 6, HSR Layout, Bengaluru',
    lat: 12.9116,
    lng: 77.6389,
    category: 'home',
  },
  {
    id: 'loc_6',
    name: 'Kempegowda International Airport (BLR)',
    address: 'Devanahalli, Bengaluru',
    lat: 13.1986,
    lng: 77.7066,
    category: 'airport',
  },
  {
    id: 'loc_7',
    name: 'Whitefield ITPL Main Gate',
    address: 'International Tech Park, Pattandur Agrahara, Bengaluru',
    lat: 12.9863,
    lng: 77.7337,
    category: 'work',
  }
];

export const INITIAL_MOCK_DRIVERS = [
  {
    id: 'drv_101',
    name: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    rating: 4.88,
    totalRides: 1420,
    vehicleType: 'cab_share',
    vehicleName: 'White Maruti Swift Dzire',
    vehicleNumber: 'KA 01 MJ 4821',
    currentLat: 12.9720,
    currentLng: 77.6350,
    status: 'online',
    isAcceptingShared: true,
  },
  {
    id: 'drv_102',
    name: 'Arjun Singh',
    phone: '+91 98123 76543',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    rating: 4.92,
    totalRides: 980,
    vehicleType: 'auto_share',
    vehicleName: 'Bajaj RE Auto',
    vehicleNumber: 'KA 05 EC 9012',
    currentLat: 12.9400,
    currentLng: 77.6200,
    status: 'online',
    isAcceptingShared: true,
  },
  {
    id: 'drv_103',
    name: 'Suresh Patil',
    phone: '+91 97456 12389',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    rating: 4.75,
    totalRides: 2150,
    vehicleType: 'bike',
    vehicleName: 'Hero Splendor Plus',
    vehicleNumber: 'KA 03 HL 1184',
    currentLat: 12.9650,
    currentLng: 77.6100,
    status: 'online',
    isAcceptingShared: false,
  },
  {
    id: 'drv_104',
    name: 'Priya Sharma',
    phone: '+91 99012 34567',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    rating: 4.95,
    totalRides: 830,
    vehicleType: 'cab_private',
    vehicleName: 'Hyundai Aura Sedan',
    vehicleNumber: 'KA 04 PC 7731',
    currentLat: 12.9300,
    currentLng: 77.6800,
    status: 'online',
    isAcceptingShared: false,
  }
];
